### PR TITLE
Bug Fix: Empty Text Handling

### LINKED ISSUE #59: Bug: Empty texts added to TextTweenManager are not managed
If you add an initially empty text to a TextTweenManager, this skips creation of the MeshData and results in inconsistent internal state (as no MeshData exists for it)

### PR DESCRIPTION
**Pull request by wallstop**
&check; Fixes #59 

# Overview 
Ok, this was really tricky. This is actually two fixes in 1.

Fix 1: Proper handling of empty texts
Fix 2: Properly handle *new texts being instantiated*

Let's dive into each one.

# Fix 1: Proper handling of empty texts
As mentioned in the referenced issue, when `TextMeshPro - Text` instances are created, they are in some weird, invalid state. Even forcing a mesh update doesn't initialize them properly. Their vertex count is different than their color/uv array counts.

To fix this, I've created an extension - `EnsureArrayIntegrity`. This both forces a mesh update and checks for this invalid state. If invalid state is detected, it does the best job it can to rectify the state and force updates.

With this fix, you can now add empty texts to a TextTweenManager and play around with the progress, then add text and have the progress applied! Great success!

But, while testing this, I noticed another problem - whenever you would add a new TMP instance to the scene, the state managed by the TextTweenManager would get corrupted somehow. Say I have a color modifier from red -> white managing one text, and progress was at 50% - light pink. When a new text is added, the text's color changes to some dark red, and stops being able to be tweened. The reason for this is that the OnChange delegate is triggered, and our MeshData runs "Update", which *copies current text state to our array*. This is wrong! The current text state is *not* the original text state, we need to somehow detect / prevent this. Which leads me to...

# Fix 2: Properly handle *new texts being instantiated*
Similar to some previous iterations of this code, I've augmented the change detection code to take in *context*. Every time there is a change, we need to properly calculate offset and length, no questions asked. However, only *sometimes* do we want to copy state between the text and our buffers.

To handle this, I pass in the context of what texts should have their state updated. In initialization, this is every text the tween manager is managing. In an on-change scenario, this is *only the text being changed*.

# The result
You can now add, remove, modify texts in any configuration - empty, initliaized, whatever you want, this thing now handles it without any errors and with the expected behavior.

### CODE REVIEW

File: Runtime/MeshArray.cs [hunk 1]
```diff
@@ -112,7 +118,7 @@ private void CreateCharData(TMP_Text text, int offset, int length)
         {
             const int vertexPerChar = 4;
             TMP_CharacterInfo[] characterInfos = text.textInfo.characterInfo;
-            int charLength = characterInfos.Length;
+            int charLength = text.textInfo.characterCount;
```
Comment (wallstop) [inline Runtime/MeshArray.cs:121]: This is the correct character count value, if you just take the array value you can get index out of range exceptions as it's a buffer, not the true character data. `characterCount` tells you how much of the buffer is valid.

File: Runtime/MeshData.cs [hunk 2]
```diff
@@ -21,18 +21,22 @@ public MeshData(TMP_Text text)
 
         public void Apply(MeshArray array)
         {
-            if (Text == null || Text.mesh == null || Text.text.Length == 0)
+            if (Text == null || Text.mesh == null || Text.text == null || Text.text.Length == 0)
```
Comment (wallstop) [inline Runtime/MeshData.cs:24]: When you add an empty text, the text string is null instead of empty, this was throwing a null reference exception :(

File: Runtime/MeshArray.cs [hunk 3]
```diff
@@ -82,27 +84,31 @@ public void CopyFrom(MeshArray source)
             _uvs2.CopyFrom(source._uvs2);
         }
 
-        public void CopyFrom(TMP_Text text, int length, int offset)
+        public void CopyFrom(TMP_Text text, int offset, int length)
```
Comment (wallstop) [inline Runtime/MeshArray.cs:87]: I unified argument order to prevent confusion between the to/from methods

File: Runtime/TextTweenManager.cs [hunk 4]
```diff
@@ -167,13 +162,11 @@ internal void Change(UnityEngine.Object obj)
...
             Allocate();
-
-            CheckForMeshChanges();
-
+            CheckForMeshChanges(obj as TMP_Text);
             Apply();
         }
 
-        internal void CheckForMeshChanges()
+        internal void CheckForMeshChanges(params TMP_Text[] textsToUpdate)
```
Comment (wallstop) [inline Runtime/TextTweenManager.cs:169]: I could optimize this, params generates a new array (allocation) if you pass it just an object. Could easily keep an array of size one around and chuck the on-change thing into it to pass here, for 0 allocations

File: Runtime/TextTweenManager.cs [hunk 5]
```diff
@@ -189,7 +182,12 @@ internal void CheckForMeshChanges()
                     int to = from + delta;
                     Move(from, to, MeshData[^1].Trail - from).Complete();
                 }
-                meshData.Update(Original, meshData.Offset);
+
+                meshData.Update(
+                    Original,
+                    meshData.Offset,
+                    copyFrom: 0 <= Array.IndexOf(textsToUpdate, meshData.Text)
```
Comment (wallstop) [inline Runtime/TextTweenManager.cs:189]: Even though this is an O(n) operation, the n in the general case (on change) is going to be =1, so this is really super fast.

It's not-so-great in the initialization case when you have lots of text, it'll be O(n^2) then, can think about how to optimize.

Comment (wallstop) [reply Runtime/TextTweenManager.cs:189]: Simplified for constant time in all cases.

File: Runtime/TextTweenManager.cs (hunk 4 above)
Comment (wallstop) [reply Runtime/TextTweenManager.cs:169]: Changed so this never allocates.

File: Runtime/MeshData.cs (hunk 2 above)
Comment (wallstop) [reply Runtime/MeshData.cs:24]: Changed to string.IsNullOrEmpty

**Comment by wallstop** [comment]
@AlicanHasirci please play around with this, I was getting some strange errors related to moving data that I was unable to reproduce reliably and I'm not sure if they're related to my change or a latent, different bug.

**Comment by AlicanHasirci** [comment]
Hey @wallstop sorry for the long hiatus and again thanks for your thorough explanation. I will be checking this PR and share my findings ASAP 👍

**Comment by AlicanHasirci** [comment]
Hey @wallstop , I'm checking the PR and I have some questions.
For the initial fix, you've mentioned that the TMP's are created with invalid state but when I check the `GenerateTextMesh` it does actually provide Colors and UVs, when I first added both UV channels my initial thought was that we were adding `vertices`,`colors` but not UVs hence the state being invalid but if this issue is still unfixed I can try to pin point the issue and remove the both UVs channels from the equation since I cannot think of an probable reason to play with them in first place and still go forward with your approach instead of using them.

About the second fix, as you've mentioned we are copying a sullied state and re-applying the changes thus doubling the changes made. We used to have a check in the `Change` method which used to check If the text that raised the event is actually being controlled by `TextTweenManager` and if so do the required changes I cannot recall why we've removed it but reintroduction can save us from redundancy.

File: Runtime/TextTweenManager.cs [hunk 6]
```diff
@@ -167,13 +163,12 @@ internal void Change(UnityEngine.Object obj)
             }
 
             Allocate();
-
-            CheckForMeshChanges();
-
+            OnChangeArguments[0] = obj as TMP_Text;
+            CheckForMeshChanges(allTexts: false, OnChangeArguments);
```
Comment (AlicanHasirci) [inline Runtime/TextTweenManager.cs:167]: I think we can skip the `allTexts` since function can be called directly without texts by which we can deduce the check is for all texts. Also since there are no cases where we pass in more than one TMP, I think we can just use `TMP_Text text = null` where we can just assume if it is `null` the check is for all.

File: Runtime/TextTweenManager.cs [hunk 7]
```diff
@@ -189,7 +184,12 @@ internal void CheckForMeshChanges()
                     int to = from + delta;
                     Move(from, to, MeshData[^1].Trail - from).Complete();
                 }
-                meshData.Update(Original, meshData.Offset);
+
+                meshData.Update(
```
Comment (AlicanHasirci) [inline Runtime/TextTweenManager.cs:188]: I will be experimenting with this, I know for a fact that on domain reload vertex count changes therefore mesh should be updated, but if the vertex count is the same (thus mesh has not been regenerated) and  also the `Move` method already updates the Offsets of succeeding `MeshData` we may avoid the Update.

**Review by AlicanHasirci — COMMENTED** [review]
I may have failed to reproduce some Fix 1 due to Unity version so if you think so, I may switch to Unity 2022.
These are some great changes and finds, I would love to talk and theorize on some evasive exception and how to reproduce them. 💯

**Comment by AlicanHasirci** [comment]
> Hey, I'm back! Been heads-down working on some game projects, finally have some time to get back to this :)

Likewise 😄  I am out of town for this week but will check it out as soon as I get back next week. Also I'm working on the non blocking async issue currently and would love to hear your feedbacks on how it's coming out.

**Comment by AlicanHasirci** [comment]
Alright this looks solid. Apparently the issue only occurs when you add the TextMeshPro_Text component to game object rather than directly adding one from ContextMenu directly (since it creates a text with 'Next Text' hence creating these arrays).

LGTM 🚀
